In [1]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

In [3]:
first_name="Garrett"
last_name="OShea"
birth_state="New Jersey"
fav_color="blue"

In [4]:
about_me=make_array(first_name,last_name,birth_state,fav_color)
about_me

array(['Garrett', 'OShea', 'New Jersey', 'blue'], dtype='<U10')

In [6]:
print(np.char.upper(about_me))

['GARRETT' 'OSHEA' 'NEW JERSEY' 'BLUE']


In [7]:
print(np.char.count(about_me,'a'))

[1 1 0 0]


In [9]:
every_other_odd=np.arange(1,42,4)
every_other_odd

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41])

In [10]:
np.sum(every_other_odd)

231

In [12]:
every_other_odd=every_other_odd.astype(float)
print(every_other_odd)

[ 1.  5.  9. 13. 17. 21. 25. 29. 33. 37. 41.]


In [13]:
np.prod(every_other_odd)

7579867420125.0

In [27]:
print(np.log(every_other_odd))

[0.         1.60943791 2.19722458 2.56494936 2.83321334 3.04452244
 3.21887582 3.36729583 3.49650756 3.61091791 3.71357207]
