In [2]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

# 1). Create an array containing 4 string elements: your first name, your last name, your birth state and favorite color.

In [3]:
#String elements
first_name="Garrett"
last_name="OShea"
birth_state="New Jersey"
fav_color="blue"

In [4]:
#Array with characteristics required
about_me=make_array(first_name,last_name,birth_state,fav_color)
about_me

array(['Garrett', 'OShea', 'New Jersey', 'blue'], dtype='<U10')

In [6]:
#numpy function to make element uppercase
print(np.char.upper(about_me))

['GARRETT' 'OSHEA' 'NEW JERSEY' 'BLUE']


In [7]:
#numpy function to count number of 'a'
print(np.char.count(about_me,'a'))

[1 1 0 0]


# 2). Create an array containing EVERY OTHER odd number starting with 1 and ending with (and including) 41.

In [4]:
#creates the array described above
every_other_odd=np.arange(1,42,4)
every_other_odd

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41])

In [10]:
#Finds the sum of the elements of the array
np.sum(every_other_odd)

231

In [12]:
#Converts the elements of the array to floats
every_other_odd=every_other_odd.astype(float)
print(every_other_odd)

[ 1.  5.  9. 13. 17. 21. 25. 29. 33. 37. 41.]


In [13]:
#Finds the product of the elements of the array
np.prod(every_other_odd)

7579867420125.0

In [27]:
#Takes the natual log of each element in the array
print(np.log(every_other_odd))

[0.         1.60943791 2.19722458 2.56494936 2.83321334 3.04452244
 3.21887582 3.36729583 3.49650756 3.61091791 3.71357207]
